### ISSUE TITLE
Sender address is constant

### ISSUE THREAD

**Issue by jasonGonzales33** [e-sportsdotcool/esports.web#151] opened 2017-11-14 13:20 UTC
UI variables returns correct values, com_sendcool recipient_id and sender_id return correct values. However, the sender address seems to be constant in sending COOL

**Comment by ppantilla** [comment] 2017-11-14 16:03
how are you verifying the sender?

**Comment by jasonGonzales33** [comment] 2017-11-14 16:30
through nanowallet

**Comment by ppantilla** [comment] 2017-11-24 03:42
jason, this has been verified as a current implem and not a bug right?

**Comment by jasonGonzales33** [comment] 2017-11-24 03:59
it is a bug, because it was working fine before

**Comment by laisee** [comment] 2017-11-24 04:24
Please check this out. Maybe it was changed to enable new users to send
cool tokens, but should be sent using actual users account

Gavin

**Comment by ppantilla** [comment] 2017-11-25 05:07
my transaction logs show that the recipient addresses match between e-sports cool account transaction log and nanowallet.  @jasonGonzales33  could you post a screenshot which shows for a particular transaction that the user is different?  

validation url: http://e-sports.cool/administrator/index.php?option=com_easysocial&view=users&layout=form&id=719

as compared to attached screenshots:
![accounttxlog.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/597ad6fe9394f7001a8e429d/125516c66e82c728ace21e0d46e997992c978dbd9bf1b34ca31fbcd6395428792c07b7692ac7b671e8107f515a0b4bff105e0d12fcf98e7ef0b36971d80d19f1c32f0e2a92624cf5f2d75dad0ba821824584b3bd8b49c8ee3e24e083864b2c53.jpg)
![walletscrnshot.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/597ad6fe9394f7001a8e429d/125516c66e82c728ace21e0d46ff95962f8797ba8cfbb150ac52e4d665043761260ea62864c7b96aea1b2c530b5f4bf8440b0e42aeaf892ba1e36a75df5d59bcc3714d36976345f3e5db55ea43a82a994e82bcbd8f4dc1ed3523e38a894b3a1a1755.jpg)

**Comment by ppantilla** [comment] 2017-11-25 13:24
or if you can send screenshots of the issue

**Comment by jasonGonzales33** [comment] 2017-11-26 05:28
Steps to produce the error: Logged in as emineminems

**Comment by jasonGonzales33** [comment] 2017-11-26 05:33
Steps to produce the error: 

>> Logged in as emineminems

>> my COOL is balance is 4091.

>> I Sent 300 COOL to user "temp" using the UI

>> Transfer is a success, but when I review emineminems (the sender) COOL
it is still 4091

When i check the transaction (using nanowallet) it appears that this address
ND2ZED4NP2MGEKPKBUOTPAXQMMJDP2BTL5NKOLVV
is the one that processed the transaction as the sender
which is wrong because emineminems is supposed to be the sender
and emineminems address is
NDXM33XVOPTX4WF4BJ44IHXTRNIKBMUIH6VDEAXE

**Comment by jasonGonzales33** [comment] 2017-11-26 05:34
![12.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59cba5677fb6900011a39579/125516c66e82c728ace21e0d46b9c6d86fc093bb80e3ba40b01faad67c1f70212d54f62f2586e27ebd442b51580a18a914590d15eee59b69f7e8682fd70541b8937f5566c73a1badbd831eb906be248f4a87b7b59801.png)

**Comment by jasonGonzales33** [comment] 2017-11-26 05:35
This applies if i am logged in as tester998, temp, tester567
so this does not regard only the user emineminems
Sender address is constant
Sender address is 
ND2ZED4NP2MGEKPKBUOTPAXQMMJDP2BTL5NKOLVV

**Comment by ppantilla** [comment] 2017-11-28 16:46
closing.  seeing no behavior as described.

**Closed by ppantilla** 2017-11-28 16:46 UTC
Labels: bug, in progress
